### ISSUE TITLE
Editing objects can get bugged when using dialogUI

### ISSUE THREAD

**Issue by GuSo187** [OnfireNetwork/dialogui#5] opened 2019-12-18 00:15 UTC
Me and some other guy on discord had the same problem we were unable to move objects that had the gizmo on, I was using godfather gamemode and he was using the mapeditor, we both had dialogUI on, I was fiddling for hours with my code as I thought that I was at fault I then noticed he wrote about a problem with dialogUI on discord, he said disabling dialogUI fixes it, and it did.

I made my object editor myself, (/editobject [objectid]) the gizmo and all would attach, but you cannot grab ahold of the X,Y,Z thingy, it is not responsive it is like there is an overlay.

If you try to pull the X,Y,Z you get the hover cursor ( The cursor you get when copying text, the straight line T looking)

Maybe there is a hidden overlay ?

**Comment by haydencarlson** [comment] 2019-12-18 05:32
I figured out that line 3 in client.lua is what's causing the mapeditor not to work
`SetWebAnchors(web, 0, 0, 1, 1)` 

I'm not sure even what that does as the dev wiki doesn't mention anything about it.
Can anyone else offer some more information on that so we can fix it?

**Comment by JanHolger** [comment] 2019-12-20 21:48
The problem is that dialogui's webui stays open all the time to allow seemless opening and closing of ui's. I'll try to fix this.

**Comment by JanHolger** [comment] 2019-12-22 17:32
Issue is fixed with the last 2 commits (:

**Closed as completed by JanHolger** 2019-12-22 17:32 UTC
